model:
    arch: segnet
data:
    dataset: ropridgeone
    train_split: train
    val_split: val
    img_rows: 1200
    img_cols: 1600
    path: /data0/qilei_chen/old_alien/AI_EYE_IMGS/ROP_DATASET_with_label/9LESIONS
training:
    train_iters: 300000
    batch_size: 2
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: segnet_ropridge_best_model.pkl
